"""empty message

Revision ID: 707a5706542f
Revises: 4369f7f4220e
Create Date: 2025-02-06 16:50:30.657254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707a5706542f'
down_revision = '4369f7f4220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_column('id_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_admin', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
