"""empty message

Revision ID: 924ed86d4a3c
Revises: 707a5706542f
Create Date: 2025-02-06 17:16:51.141509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924ed86d4a3c'
down_revision = '707a5706542f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))
        batch_op.drop_column('crated_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crated_on', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
